### ISSUE TITLE
Add test cases for display.py

### ISSUE THREAD

**Issue by sak007** [sak007/MyDollarBot-BOTGo#10]

**Comment by sak007** [comment]
v1.1 deadline missed. Moving to v1.2

**Comment by wizard-31** [comment]
flake8 --ignore=E501,W605
./test/test_display.py:14:1: E302 expected 2 blank lines, found 1
./test/test_display.py:22:1: E302 expected 2 blank lines, found 1
./test/test_display.py:29:9: E265 block comment should start with '# '
./test/test_display.py:34:1: E302 expected 2 blank lines, found 1
./test/test_display.py:43:9: E265 block comment should start with '# '
./test/test_display.py:45:1: E302 expected 2 blank lines, found 0
./test/test_display.py:54:9: E265 block comment should start with '# '
./test/test_display.py:57:1: E302 expected 2 blank lines, found 1
./test/test_display.py:67:9: E265 block comment should start with '# '


Build Failed - Please fix it before making the next commit.

**Comment by rjain09** [comment]
Fixed the check style error. Code coverage was low which was causing the build to fail. Fixed the coverage

**Comment by rjain09** [comment]
Coverage is now 85.96% for display.py. Closing the issue. Thank you!
