### ISSUE TITLE
Write test cases for budget view

### ISSUE THREAD

**Issue by sak1997** [sak007/MyDollarBot-BOTGo#21]
Please add test cases for budget view functionality.

**Comment by wizard-31** [comment]
Looks like 0e6d1e45033b08a51970660904028937fb7be491 failed the Build. Some flake8 errors. Try to run a test locally before pushing the code. Thanks!

**Comment by sak1997** [comment]
Sure, looking into it now. Thanks

**Comment by sak1997** [comment]
Fixed in Commit 45411263b0dfdc67764089fc183c7ee6d11b0668

**Comment by wizard-31** [comment]
The tests work fine and PR has been approved and merged to main.
0a155cc - Merged with main
