### ISSUE TITLE
Allow users to configure budget

### ISSUE THREAD

**Issue by sak007** [sak007/MyDollarBot-BOTGo#22]

**Comment by sak007** [comment]
Configure Budget
Commit# ae66eb404b18c68294a4bfc80f485ca1d8a73bef

 Indentation fix
Commit# 6b4d246da2eb050be67f2feb264f0323a8233c25

Removed unused file
Commit# b239fe8cc21b7d851869a7bfaa39cf1ba67ef5b1

Update mock data to support budget
Commit# 78d2400d4b8e50c6b771c8247b010afbd5e6d2cc

Indentation fix
Commit# 656fe996bea01369bbcbb5730b1523d478b3fa91

**Comment by wizard-31** [comment]
The tests work fine and PR has been approved and merged to main.
0a155cc - Merged with main
